BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ProductionOperation] ADD [endTime] DATETIME2 NOT NULL CONSTRAINT [ProductionOperation_endTime_df] DEFAULT CURRENT_TIMESTAMP,
[startTime] DATETIME2 NOT NULL CONSTRAINT [ProductionOperation_startTime_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
