BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ProductionOperation] ALTER COLUMN [endTime] DATETIME2 NULL;
ALTER TABLE [dbo].[ProductionOperation] ALTER COLUMN [startTime] DATETIME2 NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
